[program:CrawlerResponse]
command=php /opt/supervisorRC/KyX-NovoDD-backend/app/Consumers/CrawlerResponsesConsumer.php
user=www-data
autorestart=true

#[program:Crawler]
#command=./opt/supervisorRC/crawler-icts-zerorisk/crawler.sh
#user=root
#autorestart=true
