[program:CRAWLER_Input]
command=./opt/supervisorRC/crawler-icts-zerorisk/crawler.sh
user=root
autorestart=true
process_name=%(program_name)s_%(process_num)03d
stopasgroup=true
killasgroup=true
numprocs=6
